export { I18nDb };
export function t(key: any): any;
export { createT } from "@nan0web/types";
export { Language } from "./domain/Language.js";
export default i18n;
export type TFunction = import("@nan0web/types").TFunction;
import I18nDb from './I18nDb.js';
import i18n from './i18n.js';
export { i18n, defaultVocab } from "./i18n.js";
export { extract, extractFromModels, extractInfo, EXTRACT_FIELDS } from "./extract.js";
