#!/usr/bin/env node

import Logger from '@nan0web/log'
import { MemoryDB } from '@nan0web/test'
import I18nDb from '../src/I18nDb.js'
import { Language } from '../src/domain/Language.js'
import { p, errorMsg, highlight } from './components/cli/p.js'

console = new Logger()

console.warn(Logger.LOGO)
console.warn('=== @nan0web/i18n CLI Playground ===\n')

// Simulated translation dictionary logically generated by `npx i18n sync`
const db = new MemoryDB({
	predefined: new Map([
		[
			'data/uk/_/t.json',
			{
				'Language title': 'Назва мови',
				Locale: 'Локаль',
				'Locale not found': 'Локаль не знайдено',
				'Invalid locale format': 'Невірний формат локалі',
				'Language icon': 'Іконка мови',
			},
		],
		[
			'data/uk/langs.json',
			[
				{ value: 'uk', label: 'Українська' },
				{ value: 'en', label: 'English' },
			],
		],
	]),
})

await db.connect()

const i18nDb = new I18nDb({
	db,
	locale: 'uk',
	tPath: '_/t.json',
	dataDir: 'data',
	srcDir: 'src',
	langs: await db.loadDocument('data/uk/langs.json'),
})

const t = await i18nDb.createT('uk', '')
highlight(
	`🌍 Available Locales: ${i18nDb
		.getLangOptions()
		.map((l) => l.label)
		.join(', ')}\n`,
)

p('Demonstrating translated Model-as-Schema properties (prepared for ui-lit or ui-cli):')
highlight('\n--- Language Model Extracted Metadata ---')

const { title, locale, icon } = Language

p(`Title Help:      ${t(title.help)}`)
p(`Locale Help:     ${t(locale.help)}`)
p(`Icon Help:       ${t(icon.help)}`)

errorMsg(`Locale Error:    ${t(locale.errorNotFound)}`)

console.warn('\n=== End of Playground ===\n')
p(
	'Check the `./play/` folder for visual UI-cli and Web Components (ui-lit) architectural examples.',
)
