#!/usr/bin/env node

import Logger from '@nan0web/log'
import { MemoryDB } from '@nan0web/test'
import I18nDb from '../src/I18nDb.js'
import User from './models/User.js'

console = new Logger()

console.warn(Logger.LOGO)
console.warn('=== @nan0web/i18n CLI Playground ===\n')

// Simulated translation dictionary logically generated by `npx i18n sync`
const db = new MemoryDB({
	predefined: new Map([
		[
			'data/uk/_/t.json',
			{
				Username: "Ім'я користувача",
				'Enter your username': "Введіть ім'я",
				'User is not found in the system': 'Користувач не знайдений у системі',
				'Username must be at least 3 characters': "Ім'я має містити щонайменше 3 символи",
				'Internal server error while verifying': 'Внутрішня помилка при перевірці',
				'Please provide a unique username': "Будь ласка, вкажіть унікальне ім'я",
				Role: 'Роль',
				Admin: 'Адміністратор',
				Guest: 'Гість',
				'Please fill out the user registration form.': 'Будь ласка, заповніть форму реєстрації.',
				'Registration complete!': 'Реєстрацію завершено!',
			},
		],
		[
			'data/uk/langs.json',
			[
				{ value: 'uk', label: 'Українська' },
				{ value: 'en', label: 'English' },
			],
		],
	]),
})

await db.connect()

const i18nDb = new I18nDb({
	db,
	locale: 'uk',
	tPath: '_/t.json',
	dataDir: 'data',
	srcDir: 'src',
	langs: await db.loadDocument('data/uk/langs.json'),
})

const t = await i18nDb.createT('uk', '')
console.success(
	`🌍 Available Locales: ${i18nDb
		.getLangOptions()
		.map((l) => l.label)
		.join(', ')}\n`,
)

console.info('Demonstrating translated Model-as-Schema properties (prepared for ui-lit or ui-cli):')
console.success('\n--- User Form Extracted Metadata ---')

const { username, role } = User.properties

console.info(`Label:           ${t(username.label)}`)
console.info(`Placeholder:     ${t(username.placeholder)}`)
console.info(`Help:            ${t(username.help)}`)

// Note how we dynamically extract anything starting with 'error'
console.error(`Error Invalid:   ${t(username.errorInvalid)}`)
console.error(`Error Not Found: ${t(username.errorNotFound)}`)
console.error(`Error API:       ${t(username.error_api_failure)}`)

console.info('\n--- Options for Dropdown (Role) ---')
for (const opt of role.options) {
	// We translate opt.label, but NOT opt.value.
	// The variable 'opt.value' stays technical (e.g. 'admin'), while label translates.
	console.info(`Value: '${opt.value}' -> Label: '${t(opt.label)}'`)
}

console.warn('\n=== End of Playground ===\n')
console.info(
	'Check the `./play/` folder for visual UI-cli and Web Components (ui-lit) architectural examples.',
)
